//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_16_GOR.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes
    {
        public int ClothesID { get; set; }
        public string naimenov { get; set; }
        public int kolichestvo { get; set; }
        public decimal cena { get; set; }
        public int materialID { get; set; }
        public int brendID { get; set; }
        public int stranaID { get; set; }
    
        public virtual Brend Brend { get; set; }
        public virtual Material Material { get; set; }
        public virtual Strana Strana { get; set; }
    }
}
